import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RightBar from "@/components/RightBar";
import LeftBar from "@/components/LeftBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
      <div className="max-w-screen-md lg:max-w-screen-lg xl:max-w-screen-xl 2xl:max-w-screen-2xl mx-auto flex justify-between">
        <div className={"px-2 xsm:px-4 2xl:px-8"}><LeftBar/></div>
        <div className={"lg:min-w-[600px] border-x-[1px]  flex-1 border-borderGray"}>
          {children}
        </div>
        <div className={"hidden lg:flex ml-4 md:ml-8 px-2 flex-1"}><RightBar/></div>
      </div>
      </body>
    </html>
  );
}
